//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPortal.UsersWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsersWS.IUserManagementService")]
    public interface IUserManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/isValidUserCredentials", ReplyAction="http://tempuri.org/IUserManagementService/isValidUserCredentialsResponse")]
        short isValidUserCredentials(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/getCompleteUserDetails", ReplyAction="http://tempuri.org/IUserManagementService/getCompleteUserDetailsResponse")]
        System.Collections.Generic.Dictionary<string, object> getCompleteUserDetails(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/addPatient", ReplyAction="http://tempuri.org/IUserManagementService/addPatientResponse")]
        string addPatient(System.Collections.Generic.Dictionary<string, string> patientDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/addDoctor", ReplyAction="http://tempuri.org/IUserManagementService/addDoctorResponse")]
        string addDoctor(System.Collections.Generic.Dictionary<string, string> doctorDetails, string adminUsername, string adminPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagementServiceChannel : HealthPortal.UsersWS.IUserManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementServiceClient : System.ServiceModel.ClientBase<HealthPortal.UsersWS.IUserManagementService>, HealthPortal.UsersWS.IUserManagementService {
        
        public UserManagementServiceClient() {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public short isValidUserCredentials(string username, string password) {
            return base.Channel.isValidUserCredentials(username, password);
        }
        
        public System.Collections.Generic.Dictionary<string, object> getCompleteUserDetails(string username, string password) {
            return base.Channel.getCompleteUserDetails(username, password);
        }
        
        public string addPatient(System.Collections.Generic.Dictionary<string, string> patientDetails) {
            return base.Channel.addPatient(patientDetails);
        }
        
        public string addDoctor(System.Collections.Generic.Dictionary<string, string> doctorDetails, string adminUsername, string adminPassword) {
            return base.Channel.addDoctor(doctorDetails, adminUsername, adminPassword);
        }
    }
}
