//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthPortal.AdminWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminWS.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/addDepartment", ReplyAction="http://tempuri.org/IAdminService/addDepartmentResponse")]
        string addDepartment(uint hospitalID, string departmentName, string adminUsername, string adminPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/assignDoctorToDepartment", ReplyAction="http://tempuri.org/IAdminService/assignDoctorToDepartmentResponse")]
        string assignDoctorToDepartment(ulong departmentID, ulong doctorID, string adminUsername, string adminPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/getListOfHospitals", ReplyAction="http://tempuri.org/IAdminService/getListOfHospitalsResponse")]
        HealthPortalWebServices.Hospital[] getListOfHospitals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/getListOfDepartments", ReplyAction="http://tempuri.org/IAdminService/getListOfDepartmentsResponse")]
        HealthPortalWebServices.Department[] getListOfDepartments(uint hospitalID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : HealthPortal.AdminWS.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<HealthPortal.AdminWS.IAdminService>, HealthPortal.AdminWS.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addDepartment(uint hospitalID, string departmentName, string adminUsername, string adminPassword) {
            return base.Channel.addDepartment(hospitalID, departmentName, adminUsername, adminPassword);
        }
        
        public string assignDoctorToDepartment(ulong departmentID, ulong doctorID, string adminUsername, string adminPassword) {
            return base.Channel.assignDoctorToDepartment(departmentID, doctorID, adminUsername, adminPassword);
        }
        
        public HealthPortalWebServices.Hospital[] getListOfHospitals() {
            return base.Channel.getListOfHospitals();
        }
        
        public HealthPortalWebServices.Department[] getListOfDepartments(uint hospitalID) {
            return base.Channel.getListOfDepartments(hospitalID);
        }
    }
}
